# makefile

# Dimitrios Paraschas
# 1562
# Dimitrios Greasidis
# 1624
# Stefanos Papanastasiou
# 1608


.PHONY: default
default: reset_client


# reset the client
reset_client:
	rm -f configuration.json
	rm -f client.log
