# makefile

# Dimitrios Paraschas
# 1562
# Dimitrios Greasidis
# 1624
# Stefanos Papanastasiou
# 1608


.PHONY: default
default: reset_server


# reset the server
reset_server:
	rm -f configuration.json
	rm -f clients.json
	rm -f server.log
